version: "3.8"

services:
  timescale:
    image: timescale/timescaledb-ha:pg15-latest
    container_name: timescale_crypto
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: crypto
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data

volumes:
  timescale_data:
